import { describe, it, expect } from "vitest";
import { generateEpubCss, injectCssIntoHtml } from "./cssGenerator";
import { STYLE_PRESETS } from "../presets/styles";
import { buildNativePreset, deriveBookStyleSignature, emptySignature } from "./bookStyleAnalyzer";

/** CSS gốc tối thiểu của một cuốn sách "sạch", không khai báo màu nào. */
const NO_COLOR_BOOK_CSS = `
body { font-family: "Lora", serif; font-size: 1em; line-height: 1.5; text-align: justify; }
p { text-indent: 1.25em; }
`;

const COLORED_BOOK_CSS = `
body { font-family: "Lora", serif; font-size: 1.1em; line-height: 1.7; text-align: justify; color: #222; background: #fbf7ee; }
h1 { color: #7a2b2b; }
p { text-indent: 2em; }
blockquote { background-color: #eee4d0; }
`;

describe("cssGenerator — chế độ 'theo sách hiện tại'", () => {
  const fallback = STYLE_PRESETS[0];

  function adaptiveCss(css: string) {
    const signature = deriveBookStyleSignature({
      stylesheets: [{ href: "s.css", content: css }],
    });
    return {
      signature,
      css: generateEpubCss({
        preset: buildNativePreset(signature, fallback),
        fontSize: signature.fontSize ?? 16,
        lineHeight: signature.lineHeight ?? 1.7,
        firstLineIndent: signature.firstLineIndent ?? "2em",
        dropCaps: signature.dropCaps,
        textAlign: signature.textAlign ?? "justify",
        sceneDivider: signature.sceneDivider ?? "♦ ♦ ♦",
        signature,
      }),
    };
  }

  it("không ghi đè màu nền/màu chữ khi sách không khai báo", () => {
    const { signature, css } = adaptiveCss(NO_COLOR_BOOK_CSS);

    const bodyRule = css.match(/body \{([^}]*)\}/)?.[1] ?? "";
    expect(bodyRule).toContain("font-family: \"Lora\", serif;");
    expect(bodyRule).toContain("font-size: 16px;");
    expect(bodyRule).not.toContain("background-color");
    expect(bodyRule).not.toContain("color:");

    // Rule tiêu đề rỗng hoàn toàn: không có màu accent của preset nào bị áp vào
    const headingRule = css.match(/h1, h2, h3, h4, h5, h6 \{([^}]*)\}/)?.[1] ?? "";
    expect(headingRule.trim()).toBe("");

    expect(signature.colors.bg).toBeNull();
    expect(css).not.toContain(fallback.colors.bg);
    expect(css).not.toContain("blockquote {");
  });

  it("kế thừa màu gốc khi sách có khai báo", () => {
    const { css } = adaptiveCss(COLORED_BOOK_CSS);

    const bodyRule = css.match(/body \{([^}]*)\}/)?.[1] ?? "";
    expect(bodyRule).toContain("color: #222222;");
    expect(bodyRule).toContain("background-color: #fbf7ee;");

    const headingRule = css.match(/h1, h2, h3, h4, h5, h6 \{([^}]*)\}/)?.[1] ?? "";
    expect(headingRule).toContain("color: #7a2b2b;");
    expect(css).toContain("blockquote {\n  background-color: #eee4d0;");
  });

  it("vẫn phát typography để thanh trượt hoạt động", () => {
    const { css } = adaptiveCss(NO_COLOR_BOOK_CSS);
    expect(css).toContain("line-height: 1.5;");
    expect(css).toContain("text-align: justify;");
    expect(css).toContain("text-indent: 1.25em;");
  });

  it("không phát ra rule rỗng (thân thiện với epubcheck)", () => {
    for (const css of [NO_COLOR_BOOK_CSS, COLORED_BOOK_CSS]) {
      const generated = adaptiveCss(css).css;
      expect(generated).not.toMatch(/\{\s*\}/);
    }
  });

  it("không bật drop-cap khi sách gốc không dùng", () => {
    const { css } = adaptiveCss(NO_COLOR_BOOK_CSS);
    expect(css).toContain("Sách gốc không dùng drop-cap");
    expect(css).not.toContain("float: left;");
  });

  it("giữ nguyên đường xuất CSS đầy đủ cho preset thường", () => {
    const css = generateEpubCss({
      preset: fallback,
      fontSize: 16,
      lineHeight: 1.8,
      firstLineIndent: "2em",
      dropCaps: true,
      textAlign: "justify",
      sceneDivider: "☁ ☁ ☁",
    });

    expect(css).toContain("/* Generated by NiceEbook Studio");
    expect(css).toContain(fallback.colors.bg);
    expect(css).toContain("padding: 2rem 2.5rem;");
  });

  it("rơi về typography fallback khi signature rỗng nhưng vẫn không phát màu", () => {
    const signature = emptySignature();
    const css = generateEpubCss({
      preset: buildNativePreset(signature, fallback),
      fontSize: 16,
      lineHeight: fallback.lineHeight,
      firstLineIndent: fallback.firstLineIndent,
      dropCaps: false,
      textAlign: "justify",
      sceneDivider: fallback.sceneDivider,
      signature,
    });

    const bodyRule = css.match(/body \{([^}]*)\}/)?.[1] ?? "";
    expect(bodyRule).not.toContain("background-color");
    expect(css).not.toContain(fallback.colors.bg);
  });
});

describe("cssGenerator", () => {
  it("generates valid CSS with custom options and drop caps", () => {
    const preset = STYLE_PRESETS[0]; // Wuxia preset
    const css = generateEpubCss({
      preset,
      fontSize: 18,
      lineHeight: 1.85,
      firstLineIndent: "2em",
      dropCaps: true,
      textAlign: "justify",
      sceneDivider: "☁ ☁ ☁",
    });

    expect(css).toContain("font-size: 18px;");
    expect(css).toContain("line-height: 1.85;");
    expect(css).toContain("text-indent: 2em;");
    expect(css).toContain("text-align: justify;");
    expect(css).toContain(".drop-cap");
    expect(css).toContain(preset.colors.bg);
    expect(css).toContain(preset.colors.accent);
  });

  it("injects CSS into <head> properly", () => {
    const html = "<html><head><title>Chương 1</title></head><body><p>Nội dung</p></body></html>";
    const css = "body { background: #000; }";
    const injected = injectCssIntoHtml(html, css);

    expect(injected).toContain('<style id="nice-ebook-dynamic-css">body { background: #000; }</style></head>');
  });

  it("falls back to inserting <head> before <body> when <head> is missing", () => {
    const html = "<html><body><p>No head</p></body></html>";
    const css = "body { color: #fff; }";
    const injected = injectCssIntoHtml(html, css);

    expect(injected).toContain("<head><style");
    expect(injected).toContain("</head><body");
  });

  it("injects Vietnamese Google Fonts @import and uses Vietnamese font family when isVietnamese is true", () => {
    const preset = STYLE_PRESETS[0]; // Wuxia preset
    const css = generateEpubCss({
      preset,
      fontSize: 16,
      lineHeight: 1.8,
      firstLineIndent: "2em",
      dropCaps: true,
      textAlign: "justify",
      sceneDivider: "☁ ☁ ☁",
      isVietnamese: true,
    });

    expect(css).toContain("Google Fonts for Full Vietnamese Diacritics Support");
    expect(css).toContain("family=Literata");
    expect(css).toContain("family=Be+Vietnam+Pro");
    expect(css).toContain("font-family: 'Literata', 'Noto Serif', 'Times New Roman', serif;");
  });

  it("allows custom fontFamily override", () => {
    const preset = STYLE_PRESETS[0];
    const css = generateEpubCss({
      preset,
      fontSize: 16,
      lineHeight: 1.8,
      firstLineIndent: "2em",
      dropCaps: false,
      textAlign: "justify",
      sceneDivider: "♦ ♦ ♦",
      fontFamily: "'Be Vietnam Pro', sans-serif",
    });

    expect(css).toContain("font-family: 'Be Vietnam Pro', sans-serif;");
  });
});
