import { StylePreset } from "../presets/styles";

export interface GenerateCssOptions {
  preset: StylePreset;
  fontSize: number;
  lineHeight: number;
  firstLineIndent: string;
  dropCaps: boolean;
  textAlign: "justify" | "left";
  sceneDivider: string;
  customOverrides?: string;
  isVietnamese?: boolean;
  fontFamily?: string;
}

export function generateEpubCss(opts: GenerateCssOptions): string {
  const {
    preset,
    fontSize,
    lineHeight,
    firstLineIndent,
    dropCaps,
    textAlign,
    customOverrides,
    isVietnamese,
    fontFamily,
  } = opts;

  const effectiveFont = fontFamily
    ? fontFamily
    : isVietnamese && preset.vietnameseFontFamily
      ? preset.vietnameseFontFamily
      : preset.fontFamily;

  const fontImport = isVietnamese
    ? `/* Google Fonts for Full Vietnamese Diacritics Support */\n@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Literata:ital,opsz,wght@0,7..72,400;0,7..72,600;0,7..72,700;1,7..72,400&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=Merriweather:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');\n\n`
    : ``;

  const dropCapRule = dropCaps
    ? `
/* Drop Cap Styling */
.drop-cap, p.has-drop-cap::first-letter, div.chapter-body > p:first-of-type::first-letter {
  float: left;
  font-size: 3.2em;
  line-height: 0.8;
  padding-right: 0.15em;
  padding-top: 0.05em;
  color: ${preset.colors.accent};
  font-family: ${effectiveFont};
  font-weight: bold;
}
`
    : `
/* Drop Cap Disabled */
.drop-cap {
  float: none;
  font-size: 1em;
}
`;

  return `/* Generated by NiceEbook Studio - ${preset.name} */
@charset "utf-8";
${fontImport}html, body {
  margin: 0;
  padding: 0;
  background-color: ${preset.colors.bg};
  color: ${preset.colors.text};
}

body {
  font-family: ${effectiveFont};
  font-size: ${fontSize}px;
  line-height: ${lineHeight};
  text-align: ${textAlign};
  padding: 2rem 2.5rem;
  box-sizing: border-box;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
  color: ${preset.colors.accent};
  line-height: 1.3;
  margin-top: 1.8em;
  margin-bottom: 0.8em;
  font-weight: bold;
}

h1 {
  font-size: 1.8em;
  text-align: center;
  border-bottom: 1px solid ${preset.colors.border};
  padding-bottom: 0.4em;
  letter-spacing: 0.05em;
}

h2 {
  font-size: 1.4em;
  text-align: center;
}

/* Paragraphs */
p {
  margin-top: 0;
  margin-bottom: 0.6em;
  text-indent: ${firstLineIndent};
  word-break: break-word;
}

p:empty {
  display: none;
}

/* Blockquotes */
blockquote {
  margin: 1.5em 2em;
  padding: 0.8em 1.2em;
  border-left: 3px solid ${preset.colors.accent};
  background-color: ${preset.colors.cardBg};
  font-style: italic;
  opacity: 0.95;
}

/* Scene Break Dividers */
.scene-divider, hr.scene-break {
  border: none;
  text-align: center;
  margin: 2em 0;
  color: ${preset.colors.accent};
  letter-spacing: 0.4em;
  font-size: 1em;
}

/* Links */
a {
  color: ${preset.colors.accent};
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

${dropCapRule}

/* Images */
img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 1.5em auto;
  border-radius: 4px;
}

/* Kindle Word Wise Styling
   Verified against a real EPUB -> AZW3 -> EPUB conversion: a Kindle conversion normalises the
   class attribute away from <ruby> and drops font-size declared on <rt>, but keeps
   data-kindle-wordwise. So the data attribute is the durable styling hook, and the ruby text
   size is left to the reader's built-in ruby rendering. */
ruby.kindle-wordwise,
ruby[data-kindle-wordwise] {
  ruby-position: over;
  text-emphasis: none;
}
ruby.kindle-wordwise rt,
ruby[data-kindle-wordwise] rt {
  line-height: 1;
  color: ${preset.colors.accent || "#ad5a17"};
  opacity: 0.85;
  user-select: none;
  font-weight: 500;
  letter-spacing: -0.01em;
}

/* Bilingual Translation Layout */
.bilingual-original {
  opacity: 0.8 !important;
  font-size: 0.95em !important;
  margin-bottom: 0.25em !important;
}
.bilingual-translated, p[data-bilingual-for] {
  margin-top: 0 !important;
  margin-bottom: 1.2em !important;
  font-weight: 500 !important;
}

${customOverrides || ""}
`;
}

export function injectCssIntoHtml(html: string, css: string): string {
  const styleTag = `<style id="nice-ebook-dynamic-css">${css}</style>`;

  if (html.includes("</head>")) {
    return html.replace("</head>", `${styleTag}</head>`);
  } else if (html.includes("<body")) {
    return html.replace("<body", `<head>${styleTag}</head><body`);
  } else {
    return `<!DOCTYPE html><html><head>${styleTag}</head><body>${html}</body></html>`;
  }
}
