import { StylePreset } from "../presets/styles";
import type { BookStyleSignature } from "./bookStyleAnalyzer";

export interface GenerateCssOptions {
  preset: StylePreset;
  fontSize: number;
  lineHeight: number;
  firstLineIndent: string;
  dropCaps: boolean;
  textAlign: "justify" | "left";
  sceneDivider: string;
  customOverrides?: string;
  isVietnamese?: boolean;
  fontFamily?: string;
  /**
   * Signature đọc được từ CSS gốc của sách. Chỉ cần khi
   * `preset.derivedFromBook` bật (chế độ phủ thích ứng).
   */
  signature?: BookStyleSignature | null;
}

/**
 * Preset thường ⇒ stylesheet đầy đủ (giữ nguyên hành vi cũ).
 * Preset "Theo sách hiện tại" ⇒ lớp phủ thích ứng.
 */
export function generateEpubCss(opts: GenerateCssOptions): string {
  if (opts.preset?.derivedFromBook) {
    return generateAdaptiveCss(opts);
  }
  return generateFullCss(opts);
}

/**
 * Lớp phủ thích ứng: chỉ ghi đè những gì đọc được từ chính CSS của sách.
 *
 * Bất biến (được test trong cssGenerator.test.ts): KHÔNG phát ra
 * `background-color` / `color` cho body, tiêu đề hay khối trích dẫn nếu
 * signature không đọc được token tương ứng. Nhờ vậy CSS gốc của nhà xuất bản
 * vẫn quyết định phần còn lại, thay vì bị thay thế toàn bộ như trước đây.
 *
 * Typography (font, cỡ chữ, giãn dòng, canh lề, thụt đầu dòng) vẫn được phát
 * ra: đó là token đọc trực tiếp từ sách, hoặc do người dùng chỉnh bằng thanh
 * trượt Typography.
 */
function generateAdaptiveCss(opts: GenerateCssOptions): string {
  const {
    preset,
    fontSize,
    lineHeight,
    firstLineIndent,
    dropCaps,
    textAlign,
    customOverrides,
    isVietnamese,
    fontFamily,
    signature,
  } = opts;

  const effectiveFont = fontFamily
    ? fontFamily
    : isVietnamese && preset.vietnameseFontFamily
      ? preset.vietnameseFontFamily
      : preset.fontFamily;

  const colors = signature?.colors ?? {
    bg: null,
    text: null,
    accent: null,
    border: null,
    cardBg: null,
  };

  const fontImport = isVietnamese
    ? `/* Google Fonts for Full Vietnamese Diacritics Support */\n@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Literata:ital,opsz,wght@0,7..72,400;0,7..72,600;0,7..72,700;1,7..72,400&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=Merriweather:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');\n\n`
    : ``;

  const bodyColorRules = [
    colors.text ? `  color: ${colors.text};` : null,
    colors.bg ? `  background-color: ${colors.bg};` : null,
  ]
    .filter((line): line is string => Boolean(line))
    .join("\n");

  const dropCapColorRule = colors.accent ? `  color: ${colors.accent};\n` : "";

  // Rule tiêu đề chỉ tồn tại khi sách thật sự khai báo màu tiêu đề — tránh phát
  // ra rule rỗng và tránh mọi thay đổi ngoài định dạng gốc.
  const headingRule = colors.accent
    ? `\nh1, h2, h3, h4, h5, h6 {\n  color: ${colors.accent};\n}\n`
    : "";

  const blockquoteRule = colors.cardBg
    ? `\n/* Khối trích dẫn — kế thừa nền gốc của sách */\nblockquote {\n  background-color: ${colors.cardBg};\n}\n`
    : "";

  const borderRule = colors.border
    ? `\n/* Đường kẻ dưới tiêu đề — kế thừa màu gốc */\nh1 {\n  border-bottom: 1px solid ${colors.border};\n}\n`
    : "";

  const sceneDividerRule = colors.accent
    ? `\n.scene-divider, hr.scene-break {\n  border: none;\n  text-align: center;\n  margin: 2em 0;\n  color: ${colors.accent};\n  letter-spacing: 0.4em;\n  font-size: 1em;\n}\n`
    : "";

  const dropCapRule = dropCaps
    ? `\n/* Drop Cap — sách gốc đã dùng drop-cap */\n.drop-cap, p.has-drop-cap::first-letter, div.chapter-body > p:first-of-type::first-letter {\n  float: left;\n  font-size: 3.2em;\n  line-height: 0.8;\n  padding-right: 0.15em;\n  padding-top: 0.05em;\n  font-family: ${effectiveFont};\n  font-weight: bold;\n${dropCapColorRule}}\n`
    : `\n/* Sách gốc không dùng drop-cap */\n.drop-cap {\n  float: none;\n  font-size: 1em;\n}\n`;

  return `/* Generated by NiceEbook Studio — Lớp phủ thích ứng theo sách gốc */
@charset "utf-8";
${fontImport}/* Chỉ các khai báo có token đọc được từ CSS của sách mới xuất hiện ở đây. */
body {
  font-family: ${effectiveFont};
  font-size: ${fontSize}px;
  line-height: ${lineHeight};
  text-align: ${textAlign};
${bodyColorRules}
}
${headingRule}
p {
  text-indent: ${firstLineIndent};
  word-break: break-word;
}

p:empty {
  display: none;
}
${blockquoteRule}${borderRule}${sceneDividerRule}${dropCapRule}
/* Images */
img {
  max-width: 100%;
  height: auto;
}

/* Kindle Word Wise Styling
   Verified against a real EPUB -> AZW3 -> EPUB conversion: a Kindle conversion normalises the
   class attribute away from <ruby> and drops font-size declared on <rt>, but keeps
   data-kindle-wordwise. So the data attribute is the durable styling hook, and the ruby text
   size is left to the reader's built-in ruby rendering. */
ruby.kindle-wordwise,
ruby[data-kindle-wordwise] {
  ruby-position: over;
  text-emphasis: none;
}
ruby.kindle-wordwise rt,
ruby[data-kindle-wordwise] rt {
  line-height: 1;
  /* Chú thích Word Wise là markup do app tự thêm: thừa hưởng màu chữ của sách,
     hoặc màu tiêu đề nếu chính sách có khai báo — không tự đặt màu mới. */
  color: ${colors.accent || "inherit"};
  opacity: 0.85;
  user-select: none;
  font-weight: 500;
  letter-spacing: -0.01em;
}

/* Bilingual Translation Layout */
.bilingual-original {
  opacity: 0.8 !important;
  font-size: 0.95em !important;
  margin-bottom: 0.25em !important;
}
.bilingual-translated, p[data-bilingual-for] {
  margin-top: 0 !important;
  margin-bottom: 1.2em !important;
  font-weight: 500 !important;
}

${customOverrides || ""}
`;
}

function generateFullCss(opts: GenerateCssOptions): string {
  const {
    preset,
    fontSize,
    lineHeight,
    firstLineIndent,
    dropCaps,
    textAlign,
    customOverrides,
    isVietnamese,
    fontFamily,
  } = opts;

  const effectiveFont = fontFamily
    ? fontFamily
    : isVietnamese && preset.vietnameseFontFamily
      ? preset.vietnameseFontFamily
      : preset.fontFamily;

  const fontImport = isVietnamese
    ? `/* Google Fonts for Full Vietnamese Diacritics Support */\n@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Literata:ital,opsz,wght@0,7..72,400;0,7..72,600;0,7..72,700;1,7..72,400&family=Lora:ital,wght@0,400;0,600;0,700;1,400&family=Merriweather:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');\n\n`
    : ``;

  const dropCapRule = dropCaps
    ? `
/* Drop Cap Styling */
.drop-cap, p.has-drop-cap::first-letter, div.chapter-body > p:first-of-type::first-letter {
  float: left;
  font-size: 3.2em;
  line-height: 0.8;
  padding-right: 0.15em;
  padding-top: 0.05em;
  color: ${preset.colors.accent};
  font-family: ${effectiveFont};
  font-weight: bold;
}
`
    : `
/* Drop Cap Disabled */
.drop-cap {
  float: none;
  font-size: 1em;
}
`;

  return `/* Generated by NiceEbook Studio - ${preset.name} */
@charset "utf-8";
${fontImport}html, body {
  margin: 0;
  padding: 0;
  background-color: ${preset.colors.bg};
  color: ${preset.colors.text};
}

body {
  font-family: ${effectiveFont};
  font-size: ${fontSize}px;
  line-height: ${lineHeight};
  text-align: ${textAlign};
  padding: 2rem 2.5rem;
  box-sizing: border-box;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
  color: ${preset.colors.accent};
  line-height: 1.3;
  margin-top: 1.8em;
  margin-bottom: 0.8em;
  font-weight: bold;
}

h1 {
  font-size: 1.8em;
  text-align: center;
  border-bottom: 1px solid ${preset.colors.border};
  padding-bottom: 0.4em;
  letter-spacing: 0.05em;
}

h2 {
  font-size: 1.4em;
  text-align: center;
}

/* Paragraphs */
p {
  margin-top: 0;
  margin-bottom: 0.6em;
  text-indent: ${firstLineIndent};
  word-break: break-word;
}

p:empty {
  display: none;
}

/* Blockquotes */
blockquote {
  margin: 1.5em 2em;
  padding: 0.8em 1.2em;
  border-left: 3px solid ${preset.colors.accent};
  background-color: ${preset.colors.cardBg};
  font-style: italic;
  opacity: 0.95;
}

/* Scene Break Dividers */
.scene-divider, hr.scene-break {
  border: none;
  text-align: center;
  margin: 2em 0;
  color: ${preset.colors.accent};
  letter-spacing: 0.4em;
  font-size: 1em;
}

/* Links */
a {
  color: ${preset.colors.accent};
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

${dropCapRule}

/* Images */
img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 1.5em auto;
  border-radius: 4px;
}

/* Kindle Word Wise Styling
   Verified against a real EPUB -> AZW3 -> EPUB conversion: a Kindle conversion normalises the
   class attribute away from <ruby> and drops font-size declared on <rt>, but keeps
   data-kindle-wordwise. So the data attribute is the durable styling hook, and the ruby text
   size is left to the reader's built-in ruby rendering. */
ruby.kindle-wordwise,
ruby[data-kindle-wordwise] {
  ruby-position: over;
  text-emphasis: none;
}
ruby.kindle-wordwise rt,
ruby[data-kindle-wordwise] rt {
  line-height: 1;
  color: ${preset.colors.accent || "#ad5a17"};
  opacity: 0.85;
  user-select: none;
  font-weight: 500;
  letter-spacing: -0.01em;
}

/* Bilingual Translation Layout */
.bilingual-original {
  opacity: 0.8 !important;
  font-size: 0.95em !important;
  margin-bottom: 0.25em !important;
}
.bilingual-translated, p[data-bilingual-for] {
  margin-top: 0 !important;
  margin-bottom: 1.2em !important;
  font-weight: 500 !important;
}

${customOverrides || ""}
`;
}

export function injectCssIntoHtml(html: string, css: string): string {
  const styleTag = `<style id="nice-ebook-dynamic-css">${css}</style>`;

  if (html.includes("</head>")) {
    return html.replace("</head>", `${styleTag}</head>`);
  } else if (html.includes("<body")) {
    return html.replace("<body", `<head>${styleTag}</head><body`);
  } else {
    return `<!DOCTYPE html><html><head>${styleTag}</head><body>${html}</body></html>`;
  }
}
